name: Deploy to Heroku

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.12'
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Train model
      run: python noble_mid.py
    - name: Deploy to Heroku
      env:
        HEROKU_TOKEN: ${{ secrets.HEROKU_TOKEN }}
        HEROKU_APP_NAME: ${{ secrets.HEROKU_APP_NAME }}
      if: github.ref == 'refs/heads/main' && job.status == 'success'
      run: |
        curl https://cli-assets.heroku.com/install.sh | sh
        heroku git:remote -a $HEROKU_APP_NAME --force
        git push https://heroku:$HEROKU_TOKEN@git.heroku.com/$HEROKU_APP_NAME.git HEAD:main
